### ISSUE TITLE
trying to use your library

### ISSUE THREAD

**Issue by turk-jk** [utahwithak/SwiftXLSX#1]
hi there,

you are the only one who has xlsx reader in swift, how ever I was trying to use your library, but zip is not available, and if you can provide a way how to use. 

thanks

**Comment by utahwithak** [comment]
Pushed up some changes and migrated to use the latest version of the zip library. 

Try again, you'll have to init the submodule then it should build fine. 

While library works, it is currently extremely limited and slow. YMMV. I wrote it to try and get simple data (numbers/text) out for migrating to SQLite.

It is currently too slow for me and I'll likely be re-writing it to try and speed it up again. (took like 10 seconds to open up a 1.7 mb xlsx file)
